### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Amolmeh** [navin-hariharan/PAYLOAD_MASTER#1]
>
![Screenshot_20210526-162637_Termux](https://user-images.githubusercontent.com/84330667/119648660-5b5d7280-be3f-11eb-9828-5e08e15bcda1.jpg)

**Comment by navin-hariharan** [comment]
Configure Ngrok auth token

**Comment by navin-hariharan** [comment]
No response 😕

**Comment by navin-hariharan** [comment]
No response 😕

**Comment by Amolmeh** [comment]
Hi this is still showing the same error
